# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\print dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtPrintSupport import QPrintDialog, QPrinter, QPrintPreviewDialog
from PyQt5.QtWidgets import QWidget
class Ui_Dialog(QWidget):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(308, 173)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.print_file())
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        self.end_input = QtWidgets.QLineEdit(Dialog)
        self.end_input.setObjectName("end_input")
        self.gridLayout.addWidget(self.end_input, 1, 0, 1, 1)
        self.start_input = QtWidgets.QLineEdit(Dialog)
        self.start_input.setObjectName("start_input")
        self.gridLayout.addWidget(self.start_input, 0, 0, 1, 1)
        self.start = QtWidgets.QLabel(Dialog)
        self.start.setObjectName("start")
        self.gridLayout.addWidget(self.start, 0, 1, 1, 1)
        self.end = QtWidgets.QLabel(Dialog)
        self.end.setObjectName("end")
        self.gridLayout.addWidget(self.end, 1, 1, 1, 1)
        self.preview = QtWidgets.QPushButton(Dialog)
        self.preview.setObjectName("preview")
        self.preview.clicked.connect(lambda: self.print_preview_dialog())
        self.gridLayout.addWidget(self.preview, 4, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def print_file(self):
                printer = QPrinter(QPrinter.HighResolution)
                dialog = QPrintDialog(printer, None)
                if dialog.exec_() == QPrintDialog.Accepted:
                    self.start.print_(printer)
                    print(f"Printing from {self.start_input.text()} to {self.end_input.text()}")
    def print_preview(self,printer):
             file="14462.pdf"
             self.file.print_(printer)

    def print_preview_dialog(self):
             printer = QPrinter(QPrinter.HighResolution)
             preview = QPrintPreviewDialog(printer,self)
             preview.paintRequested.connect(lambda printer: self.print_preview)
             preview.exec_()
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "طباعة"))
        self.start.setText(_translate("Dialog", " من تاريخ  :"))
        self.end.setText(_translate("Dialog", "الي تاريخ  :"))
        self.preview.setText(_translate("Dialog", "معاينة"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

